In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("retail_store_sales.csv")
data

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [4]:
data.columns = (
    data.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)
)

data

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [5]:
unique_combinations = (
    data[["item", "price_per_unit"]]
    .dropna(subset=["item"])   # item NaN olanları at
    .drop_duplicates()
    .values.tolist()
)
item_price_map = dict(unique_combinations)
item_price_map

{'Item_10_PAT': 18.5,
 'Item_17_MILK': 29.0,
 'Item_12_BUT': 21.5,
 'Item_16_BEV': 27.5,
 'Item_6_FOOD': 12.5,
 'Item_1_FOOD': 5.0,
 'Item_16_FUR': 27.5,
 'Item_22_BUT': 36.5,
 'Item_3_BUT': 8.0,
 'Item_2_FOOD': 6.5,
 'Item_24_PAT': 39.5,
 'Item_16_MILK': 27.5,
 'Item_17_PAT': 29.0,
 'Item_13_EHE': 23.0,
 'Item_7_BEV': 14.0,
 'Item_4_EHE': 9.5,
 'Item_10_FOOD': 18.5,
 'Item_14_FUR': 24.5,
 'Item_20_BUT': 33.5,
 'Item_25_FUR': 41.0,
 'Item_14_FOOD': 24.5,
 'Item_22_PAT': 36.5,
 'Item_11_FOOD': 20.0,
 'Item_6_PAT': 12.5,
 'Item_21_EHE': 35.0,
 'Item_25_BEV': 41.0,
 'Item_23_FOOD': 38.0,
 'Item_10_FUR': 18.5,
 'Item_11_BEV': 20.0,
 'Item_23_BUT': 38.0,
 'Item_22_BEV': 36.5,
 'Item_10_EHE': 18.5,
 'Item_24_BUT': 39.5,
 'Item_8_BEV': 15.5,
 'Item_3_FOOD': 8.0,
 'Item_12_FOOD': 21.5,
 'Item_16_CEA': 27.5,
 'Item_11_PAT': 20.0,
 'Item_16_BUT': 27.5,
 'Item_5_CEA': 11.0,
 'Item_19_MILK': 32.0,
 'Item_23_FUR': 38.0,
 'Item_7_FUR': 14.0,
 'Item_15_CEA': 26.0,
 'Item_6_MILK': 12.5,
 'Item_24_CEA': 39.5,
 'Item_22_CEA': 36.5,
 'Item_22_FOOD': 36.5,
 'Item_2_BUT': 6.5,
 'Item_14_PAT': 24.5,
 'Item_12_PAT': 21.5,
 'Item_18_FOOD': 30.5,
 'Item_1_PAT': 5.0,
 'Item_4_BEV': 9.5,
 'Item_22_FUR': 36.5,
 'Item_7_PAT': 14.0,
 'Item_20_CEA': 33.5,
 'Item_20_FOOD': 33.5,
 'Item_11_FUR': 20.0,
 'Item_25_PAT': 41.0,
 'Item_7_FOOD': 14.0,
 'Item_21_FUR': 35.0,
 'Item_24_FUR': 39.5,
 'Item_8_MILK': 15.5,
 'Item_4_FOOD': 9.5,
 'Item_14_BEV': 24.5,
 'Item_4_PAT': 9.5,
 'Item_4_MILK': 9.5,
 'Item_7_CEA': 14.0,
 'Item_6_EHE': 12.5,
 'Item_21_BUT': 35.0,
 'Item_16_PAT': 27.5,
 'Item_25_CEA': 41.0,
 'Item_8_BUT': 15.5,
 'Item_10_CEA': 18.5,
 'Item_5_FUR': 11.0,
 'Item_9_FOOD': 17.0,
 'Item_21_CEA': 35.0,
 'Item_8_CEA': 15.5,
 'Item_8_EHE': 15.5,
 'Item_23_MILK': 38.0,
 'Item_23_BEV': 38.0,
 'Item_19_BEV': 32.0,
 'Item_20_BEV': 33.5,
 'Item_24_FOOD': 39.5,
 'Item_21_MILK': 35.0,
 'Item_6_BEV': 12.5,
 'Item_1_MILK': 5.0,
 'Item_24_MILK': 39.5,
 'Item_2_CEA': 6.5,
 'Item_18_BUT': 30.5,
 'Item_1_FUR': 5.0,
 'Item_3_MILK': 8.0,
 'Item_11_MILK': 20.0,
 'Item_13_CEA': 23.0,
 'Item_6_CEA': 12.5,
 'Item_2_FUR': 6.5,
 'Item_21_BEV': 35.0,
 'Item_8_FUR': 15.5,
 'Item_13_BUT': 23.0,
 'Item_2_BEV': 6.5,
 'Item_7_EHE': 14.0,
 'Item_14_CEA': 24.5,
 'Item_19_EHE': 32.0,
 'Item_18_CEA': 30.5,
 'Item_11_CEA': 20.0,
 'Item_17_FUR': 29.0,
 'Item_15_MILK': 26.0,
 'Item_20_EHE': 33.5,
 'Item_16_EHE': 27.5,
 'Item_23_EHE': 38.0,
 'Item_7_BUT': 14.0,
 'Item_1_EHE': 5.0,
 'Item_19_CEA': 32.0,
 'Item_25_FOOD': 41.0,
 'Item_12_EHE': 21.5,
 'Item_22_EHE': 36.5,
 'Item_13_PAT': 23.0,
 'Item_17_EHE': 29.0,
 'Item_25_BUT': 41.0,
 'Item_4_CEA': 9.5,
 'Item_2_MILK': 6.5,
 'Item_1_BUT': 5.0,
 'Item_12_BEV': 21.5,
 'Item_5_FOOD': 11.0,
 'Item_25_EHE': 41.0,
 'Item_9_CEA': 17.0,
 'Item_1_CEA': 5.0,
 'Item_15_FUR': 26.0,
 'Item_15_PAT': 26.0,
 'Item_5_EHE': 11.0,
 'Item_1_BEV': 5.0,
 'Item_17_BUT': 29.0,
 'Item_3_BEV': 8.0,
 'Item_13_FOOD': 23.0,
 'Item_11_EHE': 20.0,
 'Item_9_MILK': 17.0,
 'Item_17_FOOD': 29.0,
 'Item_20_PAT': 33.5,
 'Item_9_PAT': 17.0,
 'Item_10_BEV': 18.5,
 'Item_17_CEA': 29.0,
 'Item_8_PAT': 15.5,
 'Item_13_MILK': 23.0,
 'Item_5_BUT': 11.0,
 'Item_22_MILK': 36.5,
 'Item_4_FUR': 9.5,
 'Item_17_BEV': 29.0,
 'Item_19_PAT': 32.0,
 'Item_2_PAT': 6.5,
 'Item_14_BUT': 24.5,
 'Item_20_FUR': 33.5,
 'Item_6_BUT': 12.5,
 'Item_9_FUR': 17.0,
 'Item_12_CEA': 21.5,
 'Item_15_EHE': 26.0,
 'Item_5_PAT': 11.0,
 'Item_18_MILK': 30.5,
 'Item_6_FUR': 12.5,
 'Item_24_BEV': 39.5,
 'Item_14_MILK': 24.5,
 'Item_12_FUR': 21.5,
 'Item_18_BEV': 30.5,
 'Item_23_CEA': 38.0,
 'Item_24_EHE': 39.5,
 'Item_2_EHE': 6.5,
 'Item_23_PAT': 38.0,
 'Item_15_FOOD': 26.0,
 'Item_8_FOOD': 15.5,
 'Item_15_BEV': 26.0,
 'Item_20_MILK': 33.5,
 'Item_9_EHE': 17.0,
 'Item_11_BUT': 20.0,
 'Item_18_EHE': 30.5,
 'Item_5_MILK': 11.0,
 'Item_3_FUR': 8.0,
 'Item_19_BUT': 32.0,
 'Item_3_CEA': 8.0,
 'Item_19_FUR': 32.0,
 'Item_7_MILK': 14.0,
 'Item_9_BEV': 17.0,
 'Item_10_BUT': 18.5,
 'Item_18_FUR': 30.5,
 'Item_25_MILK': 41.0,
 'Item_4_BUT': 9.5,
 'Item_15_BUT': 26.0,
 'Item_21_PAT': 35.0,
 'Item_21_FOOD': 35.0,
 'Item_13_BEV': 23.0,
 'Item_5_BEV': 11.0,
 'Item_3_PAT': 8.0,
 'Item_13_FUR': 23.0,
 'Item_18_PAT': 30.5,
 'Item_12_MILK': 21.5,
 'Item_10_MILK': 18.5,
 'Item_16_FOOD': 27.5,
 'Item_19_FOOD': 32.0,
 'Item_14_EHE': 24.5,
 'Item_3_EHE': 8.0,
 'Item_9_BUT': 17.0}

In [6]:
data["price_per_unit"] = data["total_spent"] / data["quantity"]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    12575 non-null  object
 1   customer_id       12575 non-null  object
 2   category          12575 non-null  object
 3   item              11362 non-null  object
 4   price_per_unit    11971 non-null  float64
 5   quantity          11971 non-null  float64
 6   total_spent       11971 non-null  float64
 7   payment_method    12575 non-null  object
 8   location          12575 non-null  object
 9   transaction_date  12575 non-null  object
 10  discount_applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [7]:
price_item_map = {v: k for k, v in item_price_map.items()}

mask = data["item"].isna()

data.loc[mask, "item"] = (
    data.loc[mask, "price_per_unit"]
    .map(price_item_map)
)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    12575 non-null  object
 1   customer_id       12575 non-null  object
 2   category          12575 non-null  object
 3   item              11971 non-null  object
 4   price_per_unit    11971 non-null  float64
 5   quantity          11971 non-null  float64
 6   total_spent       11971 non-null  float64
 7   payment_method    12575 non-null  object
 8   location          12575 non-null  object
 9   transaction_date  12575 non-null  object
 10  discount_applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [8]:
data = data.drop_duplicates()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    12575 non-null  object
 1   customer_id       12575 non-null  object
 2   category          12575 non-null  object
 3   item              11971 non-null  object
 4   price_per_unit    11971 non-null  float64
 5   quantity          11971 non-null  float64
 6   total_spent       11971 non-null  float64
 7   payment_method    12575 non-null  object
 8   location          12575 non-null  object
 9   transaction_date  12575 non-null  object
 10  discount_applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [9]:
data[data["discount_applied"] == True]

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,NaN,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
10,TXN_8776416,CUST_22,Butchers,Item_3_BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
...,...,...,...,...,...,...,...,...,...,...,...
12559,TXN_5604451,CUST_08,Food,Item_21_FOOD,35.0,8.0,280.0,Cash,In-store,2023-12-28,True
12560,TXN_6972612,CUST_20,Electric household essentials,Item_12_EHE,21.5,8.0,172.0,Digital Wallet,Online,2024-10-14,True
12561,TXN_6960333,CUST_12,Computers and electric accessories,Item_17_CEA,29.0,2.0,58.0,Credit Card,Online,2024-12-12,True
12563,TXN_5394856,CUST_08,Patisserie,Item_17_PAT,29.0,2.0,58.0,Digital Wallet,Online,2024-10-24,True
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True

In [10]:
data = data.dropna(subset = "price_per_unit")
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11971 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    11971 non-null  object
 1   customer_id       11971 non-null  object
 2   category          11971 non-null  object
 3   item              11971 non-null  object
 4   price_per_unit    11971 non-null  float64
 5   quantity          11971 non-null  float64
 6   total_spent       11971 non-null  float64
 7   payment_method    11971 non-null  object
 8   location          11971 non-null  object
 9   transaction_date  11971 non-null  object
 10  discount_applied  7983 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB